name: Publish SDK (GH Packages + npm, private)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write      # publish to GitHub Packages
  id-token: write      # keep enabled; useful if you switch to npm Trusted Publishing later

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # ---------- Publish to GitHub Packages (private) ----------
      # This uses the same package name @benji-money/connect-sdk
      - name: Configure GH registry for @benji-money scope
        run: npm config set @benji-money:registry https://npm.pkg.github.com

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ---------- Publish to npm (private) ----------
      # Private scoped packages require a paid npm org and --access restricted
      - name: Publish to npm (restricted/private)
        run: npm publish --access restricted --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
